Supporting till version 6.6.2.
sensu/sensu-go-ansible pull request #305
Opened 2021-12-10 09:35 UTC by juremedvesek

Updated linux containers to test, and windows msi-s. Is it ok to also update 6.2.5 to 6.2.7?
Also docker images for linux must still be pushed to quay repository.

Test were executed. Specific change was inside integration tests where i had comented 'pull=true', since i had to use local packages,
because I did not pushed images to quay yet.

2021-12-12 14:01 UTC, tadeboro requested changes
I added some inline comments about the changes, but there is one more thing I would like to see addressed. Can we split this PR into two PRs: one for updating windows versions, and another one for updating docker images and CI config? Thanks!

2021-12-13 06:58 UTC, juremedvesek commented on docker/sensu-6.2.7.docker
> +]
Ok will split

2021-12-13 06:59 UTC, juremedvesek commented on docker/sensu-6.4.3.docker
> +]
Agreed - my bad

2021-12-13 07:00 UTC, juremedvesek commented on roles/install/vars/Windows.yml
> +    version: 6.6.2
Will probably create separate PR - need to check what "update_windows_version" produces, and if we need to add some "skip" logic there for old versions.

2021-12-13 22:16 UTC, tadeboro commented
Closing as this was implemented in #307 and #306

2021-12-13 22:16 UTC, closed without merging